insert into public.trains (model, capacity) values ('Pilot', 426);
insert into public.trains (model, capacity) values ('Explorer', 395);
insert into public.trains (model, capacity) values ('SVX', 220);
insert into public.trains (model, capacity) values ('Pajero', 415);
insert into public.trains (model, capacity) values ('SL-Class', 110);
insert into public.trains (model, capacity) values ('Dakota', 240);
insert into public.trains (model, capacity) values ('9-4X', 200);
insert into public.trains (model, capacity) values ('2500 Club Coupe', 153);
insert into public.trains (model, capacity) values ('300CE', 120);
insert into public.trains (model, capacity) values ('Camry', 469);
insert into public.trains (model, capacity) values ('Hombre', 323);
insert into public.trains (model, capacity) values ('SLK-Class', 311);
insert into public.trains (model, capacity) values ('Taurus', 253);
insert into public.trains (model, capacity) values ('Touareg', 385);
insert into public.trains (model, capacity) values ('tC', 245);
insert into public.trains (model, capacity) values ('XC60', 489);
insert into public.trains (model, capacity) values ('S10', 135);
insert into public.trains (model, capacity) values ('Ram 2500', 470);
insert into public.trains (model, capacity) values ('F150', 298);
insert into public.trains (model, capacity) values ('Vandura 2500', 203);
insert into public.trains (model, capacity) values ('Spider', 228);
insert into public.trains (model, capacity) values ('Neon', 430);
insert into public.trains (model, capacity) values ('MX-6', 170);
insert into public.trains (model, capacity) values ('Town & Country', 201);
insert into public.trains (model, capacity) values ('Fleetwood', 157);
insert into public.trains (model, capacity) values ('Town Car', 235);
insert into public.trains (model, capacity) values ('Chariot', 347);
insert into public.trains (model, capacity) values ('Quest', 320);
insert into public.trains (model, capacity) values ('645', 453);
insert into public.trains (model, capacity) values ('Passat', 121);
insert into public.trains (model, capacity) values ('900', 368);
insert into public.trains (model, capacity) values ('RL', 444);
insert into public.trains (model, capacity) values ('Dakota Club', 330);
insert into public.trains (model, capacity) values ('Civic Si', 149);
insert into public.trains (model, capacity) values ('Chariot', 206);
insert into public.trains (model, capacity) values ('Crown Victoria', 196);
insert into public.trains (model, capacity) values ('400E', 376);
insert into public.trains (model, capacity) values ('Discovery', 341);
insert into public.trains (model, capacity) values ('B2600', 103);
insert into public.trains (model, capacity) values ('Millenia', 344);
insert into public.trains (model, capacity) values ('Altima', 414);
insert into public.trains (model, capacity) values ('CC', 252);
insert into public.trains (model, capacity) values ('Tribeca', 216);
insert into public.trains (model, capacity) values ('GTO', 286);
insert into public.trains (model, capacity) values ('Astro', 405);
insert into public.trains (model, capacity) values ('XLR', 229);
insert into public.trains (model, capacity) values ('3000GT', 233);
insert into public.trains (model, capacity) values ('3500 Club Coupe', 298);
insert into public.trains (model, capacity) values ('Shadow', 248);
insert into public.trains (model, capacity) values ('DTS', 187);
insert into public.trains (model, capacity) values ('Elantra', 249);
insert into public.trains (model, capacity) values ('Ascender', 404);
insert into public.trains (model, capacity) values ('Colt', 243);
insert into public.trains (model, capacity) values ('Eclipse', 241);
insert into public.trains (model, capacity) values ('Bonneville', 267);
insert into public.trains (model, capacity) values ('323', 397);
insert into public.trains (model, capacity) values ('Camaro', 150);
insert into public.trains (model, capacity) values ('V70', 323);
insert into public.trains (model, capacity) values ('Yukon XL 1500', 361);
insert into public.trains (model, capacity) values ('Cayenne', 366);
insert into public.trains (model, capacity) values ('FX', 181);
insert into public.trains (model, capacity) values ('Beetle', 329);
insert into public.trains (model, capacity) values ('Explorer', 353);
insert into public.trains (model, capacity) values ('Suburban 2500', 299);
insert into public.trains (model, capacity) values ('RDX', 347);
insert into public.trains (model, capacity) values ('Grand Prix', 264);
insert into public.trains (model, capacity) values ('Quest', 139);
insert into public.trains (model, capacity) values ('Range Rover', 465);
insert into public.trains (model, capacity) values ('Savana', 187);
insert into public.trains (model, capacity) values ('Miata MX-5', 320);
insert into public.trains (model, capacity) values ('Econoline E350', 348);
insert into public.trains (model, capacity) values ('RL', 181);
insert into public.trains (model, capacity) values ('Dakota', 454);
insert into public.trains (model, capacity) values ('Cobalt', 466);
insert into public.trains (model, capacity) values ('CX-7', 187);
insert into public.trains (model, capacity) values ('Previa', 471);
insert into public.trains (model, capacity) values ('Expedition', 438);
insert into public.trains (model, capacity) values ('Prizm', 500);
insert into public.trains (model, capacity) values ('STS', 201);
insert into public.trains (model, capacity) values ('Legacy', 150);
insert into public.trains (model, capacity) values ('Range Rover', 454);
insert into public.trains (model, capacity) values ('Ram 2500', 336);
insert into public.trains (model, capacity) values ('Mustang', 166);
insert into public.trains (model, capacity) values ('Grand Vitara', 325);
insert into public.trains (model, capacity) values ('Club Wagon', 242);
insert into public.trains (model, capacity) values ('Lanos', 489);
insert into public.trains (model, capacity) values ('Ram Van 3500', 307);
insert into public.trains (model, capacity) values ('Mustang', 101);
insert into public.trains (model, capacity) values ('Tiburon', 245);
insert into public.trains (model, capacity) values ('S-Class', 197);
insert into public.trains (model, capacity) values ('Eos', 301);
insert into public.trains (model, capacity) values ('DTS', 187);
insert into public.trains (model, capacity) values ('Ram 2500', 452);
insert into public.trains (model, capacity) values ('LeMans', 343);
insert into public.trains (model, capacity) values ('Escort', 239);
insert into public.trains (model, capacity) values ('Grand Cherokee', 436);
insert into public.trains (model, capacity) values ('Altima', 359);
insert into public.trains (model, capacity) values ('Tribeca', 285);
insert into public.trains (model, capacity) values ('Mazda6 Sport', 219);
insert into public.trains (model, capacity) values ('Genesis', 150);
