insert into public.stations (name, address) values ('Jamaica', '1 Westend Center');
insert into public.stations (name, address) values ('China', '672 Warner Crossing');
insert into public.stations (name, address) values ('China', '0 Comanche Hill');
insert into public.stations (name, address) values ('Philippines', '1759 Lakeland Road');
insert into public.stations (name, address) values ('Vietnam', '31317 Moland Circle');
insert into public.stations (name, address) values ('France', '7154 Cardinal Junction');
insert into public.stations (name, address) values ('Poland', '124 Banding Road');
insert into public.stations (name, address) values ('Russia', '65763 Little Fleur Crossing');
insert into public.stations (name, address) values ('Finland', '0993 Amoth Park');
insert into public.stations (name, address) values ('Canada', '35670 Carpenter Plaza');
insert into public.stations (name, address) values ('China', '1 Manley Terrace');
insert into public.stations (name, address) values ('Portugal', '88 Old Gate Plaza');
insert into public.stations (name, address) values ('Ireland', '6 Macpherson Crossing');
insert into public.stations (name, address) values ('Portugal', '60 Fallview Terrace');
insert into public.stations (name, address) values ('Russia', '1 Hermina Center');
insert into public.stations (name, address) values ('Czech Republic', '750 Doe Crossing Plaza');
insert into public.stations (name, address) values ('Indonesia', '3 Pierstorff Drive');
insert into public.stations (name, address) values ('Nepal', '7 Eastwood Pass');
insert into public.stations (name, address) values ('Brazil', '821 Utah Parkway');
insert into public.stations (name, address) values ('Guatemala', '63 Emmet Place');
insert into public.stations (name, address) values ('Egypt', '0580 Arapahoe Way');
insert into public.stations (name, address) values ('Macedonia', '29505 Utah Trail');
insert into public.stations (name, address) values ('China', '1 Golf Course Hill');
insert into public.stations (name, address) values ('Philippines', '902 Scofield Crossing');
insert into public.stations (name, address) values ('Russia', '8 Spenser Place');
insert into public.stations (name, address) values ('Poland', '634 Center Junction');
insert into public.stations (name, address) values ('China', '06035 Bowman Alley');
insert into public.stations (name, address) values ('China', '15 Lunder Pass');
insert into public.stations (name, address) values ('Peru', '4 Maple Wood Hill');
insert into public.stations (name, address) values ('China', '03523 Marquette Hill');
insert into public.stations (name, address) values ('Philippines', '73442 Manufacturers Terrace');
insert into public.stations (name, address) values ('Madagascar', '818 Londonderry Point');
insert into public.stations (name, address) values ('Indonesia', '6 Eggendart Drive');
insert into public.stations (name, address) values ('Indonesia', '964 Elka Hill');
insert into public.stations (name, address) values ('Croatia', '9 Canary Place');
insert into public.stations (name, address) values ('Ukraine', '009 Alpine Street');
insert into public.stations (name, address) values ('Nepal', '563 Hooker Junction');
insert into public.stations (name, address) values ('United States', '3382 Sachs Junction');
insert into public.stations (name, address) values ('Thailand', '37 Transport Park');
insert into public.stations (name, address) values ('United States', '3 Old Shore Point');
insert into public.stations (name, address) values ('Czech Republic', '489 Mayer Plaza');
insert into public.stations (name, address) values ('France', '38 Mcbride Circle');
insert into public.stations (name, address) values ('Ukraine', '96 Sachs Junction');
insert into public.stations (name, address) values ('Kazakhstan', '040 La Follette Trail');
insert into public.stations (name, address) values ('South Africa', '88 International Terrace');
insert into public.stations (name, address) values ('Argentina', '024 Mendota Alley');
insert into public.stations (name, address) values ('Guatemala', '313 Nova Plaza');
insert into public.stations (name, address) values ('China', '1 Mccormick Pass');
insert into public.stations (name, address) values ('France', '1 Sachtjen Place');
insert into public.stations (name, address) values ('China', '61 Miller Parkway');
insert into public.stations (name, address) values ('Indonesia', '1 Quincy Park');
insert into public.stations (name, address) values ('Russia', '423 Grim Way');
insert into public.stations (name, address) values ('China', '4886 Anhalt Lane');
insert into public.stations (name, address) values ('Canada', '182 Buena Vista Point');
insert into public.stations (name, address) values ('Indonesia', '8 Melody Drive');
insert into public.stations (name, address) values ('United States', '18359 Raven Lane');
insert into public.stations (name, address) values ('Portugal', '079 Harbort Drive');
insert into public.stations (name, address) values ('Russia', '03461 Corry Terrace');
insert into public.stations (name, address) values ('Brazil', '25 Charing Cross Pass');
insert into public.stations (name, address) values ('Serbia', '2237 Magdeline Point');
insert into public.stations (name, address) values ('Russia', '81 Anzinger Circle');
insert into public.stations (name, address) values ('Philippines', '89757 Dawn Court');
insert into public.stations (name, address) values ('Argentina', '0 Hintze Terrace');
insert into public.stations (name, address) values ('Iraq', '90561 Union Trail');
insert into public.stations (name, address) values ('Pakistan', '2 Buena Vista Junction');
insert into public.stations (name, address) values ('Georgia', '772 Badeau Park');
insert into public.stations (name, address) values ('Thailand', '49 Red Cloud Court');
insert into public.stations (name, address) values ('Botswana', '1678 Myrtle Court');
insert into public.stations (name, address) values ('China', '0 Arapahoe Trail');
insert into public.stations (name, address) values ('China', '25 Knutson Plaza');
insert into public.stations (name, address) values ('Finland', '2083 Birchwood Way');
insert into public.stations (name, address) values ('Azerbaijan', '9827 Hooker Lane');
insert into public.stations (name, address) values ('China', '2445 Schurz Parkway');
insert into public.stations (name, address) values ('Ukraine', '1 Bonner Park');
insert into public.stations (name, address) values ('Russia', '129 Bartillon Place');
insert into public.stations (name, address) values ('Belarus', '40 Autumn Leaf Trail');
insert into public.stations (name, address) values ('Peru', '4506 Meadow Ridge Terrace');
insert into public.stations (name, address) values ('Ukraine', '750 Crownhardt Hill');
insert into public.stations (name, address) values ('Poland', '401 Lakewood Gardens Parkway');
insert into public.stations (name, address) values ('Indonesia', '44 Welch Drive');
insert into public.stations (name, address) values ('China', '8 8th Circle');
insert into public.stations (name, address) values ('Sweden', '87089 Monterey Court');
insert into public.stations (name, address) values ('Nigeria', '4856 Paget Center');
insert into public.stations (name, address) values ('Russia', '64 Pleasure Park');
insert into public.stations (name, address) values ('China', '01 Grasskamp Circle');
insert into public.stations (name, address) values ('Indonesia', '38 Mesta Center');
insert into public.stations (name, address) values ('China', '099 Holmberg Street');
insert into public.stations (name, address) values ('Brazil', '01 Rieder Hill');
insert into public.stations (name, address) values ('Peru', '51019 Lighthouse Bay Crossing');
insert into public.stations (name, address) values ('France', '96385 Dakota Place');
insert into public.stations (name, address) values ('France', '2 Banding Alley');
insert into public.stations (name, address) values ('China', '0 Maryland Crossing');
insert into public.stations (name, address) values ('China', '28588 Forest Dale Point');
insert into public.stations (name, address) values ('Brazil', '60 Northfield Pass');
insert into public.stations (name, address) values ('United Kingdom', '1293 Bayside Lane');
insert into public.stations (name, address) values ('Russia', '717 Clove Hill');
insert into public.stations (name, address) values ('New Zealand', '489 Tomscot Way');
insert into public.stations (name, address) values ('Poland', '9684 Carioca Road');
insert into public.stations (name, address) values ('Canada', '9 Bobwhite Trail');
insert into public.stations (name, address) values ('Japan', '1794 Eastlawn Drive');